FROM nginx:1.25.1-bookworm AS NGINX

LABEL \
  # Authors or maintainers of the image.
  org.opencontainers.image.authors="Balaji Pothula <balaji@significo.com>" \
  # Image reference of the image.
  org.opencontainers.image.base.name="nginx:1.25.1-bookworm" \
  # Title or name for the image.
  org.opencontainers.image.title="nginx:1.25.1" \
  # Description or summary of the image.
  org.opencontainers.image.description="NGINX 1.25.1 - Reverse Proxy Server"

RUN \
  # Exit immediately if any command fails.
  set -e; \
  # Disable the interactive prompts and allows for automate.
  export DEBIAN_FRONTEND=noninteractive; \
  # Update the package lists for repositories.
  apt --yes --quiet update && \
  # Upgrade the packages.
  apt --yes --quiet upgrade && \
  # Install the required dependencies and packages.
  apt --yes --quiet install \
  certbot \
  locales && \
  # Remove the package files from the cache.
  apt --yes --quiet autoclean && \
  # Remove Debian based packages.
  rm -rf /var/lib/apt/lists/* && \
  # Update locale definition file, language English and localization US. 
  localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8

# Set default language English and localization US.
ENV LANG en_US.utf8

# Creates a mount point for persistent data in the container.
VOLUME ["/webapp"]

# Container will listen on port 443 using TCP.
EXPOSE 443/tcp
